services:
  - type: web
    name: jobmate-backend
    env: docker
    dockerContext: .
    dockerfile: Dockerfile
    envVars:
      - key: PORT
        value: 10000
      - key: PYTHONUNBUFFERED
        value: 1
